### PR TITLE
New multi-arch github workflow

### PR DESCRIPTION
**Pull request by nashant**
Unified multi-arch docker build

### CODE REVIEW

**Comment by nashant** [comment]
Currently got latest running on a raspberry pi

**Comment by vassilvk** [comment]
Closes #70.

**Comment by vassilvk** [comment]
Thank you @nashant!

Several notes:
- Please remove `build/deploy-image.sh` as it is not used anymore.
- Modify `Makefile` to make the `docker-build` target work with the new `Dockerfile` by passing in `amd64` as `TARGETARCH` when calling `docker build`.
- Do we need `TARGETOS` in `Dockerfile`? If not used, can it be removed?
- Target DockerHub repo `kubemod/kubemod` in `.github/workflows/main-workflow.yaml`, line 53.

**Comment by nashant** [comment]
All done

**Pull request merged**
