### PR TITLE
Update crt version to 1.1.2

### LINKED ISSUE #79: Update crt version to 1.1.2
As a followup to kubemod/kubemod-crt#6, update the version of CRT used by the bundle to 1.1.2

### PR DESCRIPTION
**Pull request by gmahomarf**
As a followup to kubemod/kubemod-crt#6, update the version of CRT used by the bundle.

Closes #79

### CODE REVIEW

**Comment by vassilvk** [comment]
Hi @gmahomarf, thanks for the PR!

Two notes:
- Please create an issue for this PR so that I can refer to it in CHANGELOG and the release notes of the next release.
- The way to up the version of `kubemod-crt` is to modify file `config/kubemod-crt/kubemod-crt-job.yaml` and then run `make bundle` to regenerate `bundle.yaml`. Please make the appropriate changes.

**Comment by gmahomarf** [comment]
@vassilvk I did as you requested, however it resulted in additional changes to the bundle. Would you like me to cherry-pick the changes relevant to the version update only?

**Comment by vassilvk** [comment]
@gmahomarf, sorry, my bad - please don't rebuild the bundle - only change kubemod-crt-job.yaml.
Hopefully I'll have time to test over the weekend and release kubemod v0.14.0 with your changes.

**Comment by gmahomarf** [comment]
Done. Thanks for the quick turnaround

**Comment by vassilvk** [comment]
Closes #79

**Pull request merged**
