### PR TITLE
feat: native unified diffs

### PR DESCRIPTION
**Pull request by jamiecore**
how u feel about this ?

### CODE REVIEW

**Comment by jamiecore** [comment]
https://github.com/kubemod/kubemod/issues/56

**Comment by vassilvk** [comment]
I feel great about this :)
I spent days trying to find a proper unified diff implementation in go until I gave up and implemented one based on command diff.
I hate to see my memfile tricks go, but this is obviously a much better solution ;)

**Comment by vassilvk** [comment]
Closes #56.

**Comment by jamiecore** [comment]
i enjoyed ur memfiles trix 👍  but ❤️ to see them go 🤣

**Pull request merged**
